version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db
    privileged: true
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - "odoo-db:/var/lib/postgresql/data"

  odoo:
    build:
      context: ./odoo19
      dockerfile: Dockerfile
    container_name: odoo
    privileged: true
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - PORT=5432
    volumes:
      - ~/Documents/odoo/addons:/mnt/extra-addons
      - "odoo-data:/var/lib/odoo"
      - "odoo-vscode:/opt/odoo/.vscode"
      - "odoo-home:/root"
      - "odoo-custom-addons:/opt/odoo/custom-addons"
    restart: always

# use existing volumes
volumes:
  odoo-vscode:
  odoo-home:
  odoo-custom-addons:
  odoo-db:
  odoo-data:
